"""Type stubs for the native core `pyregtab._core`."""

from enum import Enum
from typing import Any, Callable, Iterable, Mapping, Optional, Sequence, Union

UNBOUNDED: int

# ---------------------------------------------------------------- enums

class FontFamily(Enum):
    SERIF = ...
    SANS_SERIF = ...
    MONOSPACED = ...

class HorizontalAlignment(Enum):
    LEFT = ...
    CENTER = ...
    RIGHT = ...
    JUSTIFY = ...

class VerticalAlignment(Enum):
    TOP = ...
    CENTER = ...
    BOTTOM = ...
    JUSTIFY = ...

class ItemType(Enum):
    VALUE = ...
    ATTRIBUTE = ...
    AUXILIARY = ...

class ItemDerivationDirective(Enum):
    VAL = ...
    ATTR = ...
    AUX = ...
    SKIP = ...

class OperationType(Enum):
    FILL = ...
    PREFIX = ...
    SUFFIX = ...
    AVP = ...
    REC = ...
    JOIN = ...

class TraversalOrder(Enum):
    ROW_MAJOR = ...
    REVERSE_ROW_MAJOR = ...
    COLUMN_MAJOR = ...
    REVERSE_COLUMN_MAJOR = ...

class CellDerivedProviderKind(Enum):
    UNRESTRICTED = ...
    VAL = ...
    ATTR = ...
    AUX = ...

class ContextDerivedProviderKind(Enum):
    UNRESTRICTED = ...
    VAL = ...
    ATTR = ...
    AUX = ...

class SchemaConstructionStrategy(Enum):
    RECORD_FIRST = ...
    POSITION_FIRST = ...

class ActionApplicationStrategy(Enum):
    ROW_FIRST = ...
    COLUMN_FIRST = ...

# ---------------------------------------------------------------- syntax

class GridPosition:
    row: int
    col: int
    def __init__(self, row: int, col: int) -> None: ...

class BoundingBox:
    top_row: int
    left_col: int
    bottom_row: int
    right_col: int
    def row_span(self) -> int: ...
    def col_span(self) -> int: ...

class CellColor:
    r: int
    g: int
    b: int
    BLACK: CellColor
    WHITE: CellColor
    def __init__(self, r: int, g: int, b: int) -> None: ...

class Cell:
    row: int
    col: int
    pos: GridPosition
    bbox: BoundingBox
    merged: bool
    text: str
    text_blank: bool
    text_multiline: bool
    text_indent: int
    font_family: FontFamily
    font_bold: bool
    font_italic: bool
    font_strikeout: bool
    font_underline: bool
    horz_align: HorizontalAlignment
    vert_align: VerticalAlignment
    left_border: bool
    top_border: bool
    right_border: bool
    bottom_border: bool
    bg_color: CellColor
    fg_color: CellColor
    rotation: float
    parent_row: Row
    subtable: Optional[Subtable]
    subrow: Optional[Subrow]
    def set_text(self, text: str) -> None: ...

class Row:
    index: int
    subtable: Optional[Subtable]
    def subrows(self) -> list[Subrow]: ...

class Subrow:
    col_start: int
    col_end: int
    def cells(self) -> list[Cell]: ...

class Subtable:
    row_start: int
    row_end: int
    def rows(self) -> list[Row]: ...

class TableSyntax:
    num_rows: int
    num_cols: int
    def __init__(self, num_rows: int, num_cols: int) -> None: ...
    def cell(self, row: int, col: int) -> Cell: ...
    def get_cell(self, row: int, col: int) -> Cell: ...
    def row(self, index: int) -> Row: ...
    def rows(self) -> list[Row]: ...
    def subtables(self) -> list[Subtable]: ...
    def all_cells(self) -> list[Cell]: ...
    def define_subtables(self, *boundaries: int) -> None: ...
    def define_subrow(self, row_index: int, col_start: int, col_end: int) -> None: ...

# ---------------------------------------------------------------- items

class CellDerivedItem:
    str: str
    tags: list[str]
    index: int
    type_: ItemType
    cell: Cell
    def has_tag(self, tag: str) -> bool: ...

class ContextDerivedItem:
    str: str
    type_: ItemType
    const_value: Optional[str]
    def __init__(
        self, s: str, ty: ItemType, const_value: Optional[str] = None
    ) -> None: ...

class TableSemantics:
    def cell_derived_items(self) -> list[CellDerivedItem]: ...
    def context_derived_items(self) -> list[ContextDerivedItem]: ...
    def action_count(self) -> int: ...

class InterpretableTable:
    syntax: TableSyntax
    semantics: TableSemantics

# ---------------------------------------------------------------- recordset

class Schema:
    attributes: list[str]
    def __init__(self, attributes: Sequence[str]) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def index_of(self, attribute: str) -> int: ...
    def contains(self, attribute: str) -> bool: ...
    def __contains__(self, attribute: str) -> bool: ...

class Record:
    schema: Schema
    def get(self, key: Union[str, int]) -> Optional[str]: ...
    def __getitem__(self, key: Union[str, int]) -> Optional[str]: ...
    def values(self) -> dict[str, Optional[str]]: ...

class Recordset:
    schema: Schema
    records: list[Record]
    def __init__(
        self, schema: Schema, records: Sequence[Mapping[str, Optional[str]]]
    ) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def get(self, index: int) -> Record: ...
    def __getitem__(self, index: int) -> Record: ...
    def to_pandas(self) -> Any: ...

# ---------------------------------------------------------------- spec

class Quantifier:
    kind: str
    n: int
    @staticmethod
    def one() -> Quantifier: ...
    @staticmethod
    def zero_or_one() -> Quantifier: ...
    @staticmethod
    def one_or_more() -> Quantifier: ...
    @staticmethod
    def zero_or_more() -> Quantifier: ...
    @staticmethod
    def exactly(n: int) -> Quantifier: ...
    def min(self) -> int: ...
    def max(self) -> int: ...

class CellPredicate:
    @staticmethod
    def blank() -> CellPredicate: ...
    @staticmethod
    def not_blank() -> CellPredicate: ...
    @staticmethod
    def regex_matched(pattern: str) -> CellPredicate: ...
    @staticmethod
    def not_regex_matched(pattern: str) -> CellPredicate: ...
    @staticmethod
    def contains(substring: str) -> CellPredicate: ...
    @staticmethod
    def not_contains(substring: str) -> CellPredicate: ...
    @staticmethod
    def external(name: str, predicate: Callable[[Cell], bool]) -> CellPredicate: ...
    @staticmethod
    def custom(description: str, predicate: Callable[[Cell], bool]) -> CellPredicate: ...
    def to_rtl(self) -> str: ...
    def test(self, cell: Cell) -> bool: ...

class CellMatchCondition:
    cell_predicate: CellPredicate
    def __init__(self, cell_predicate: CellPredicate) -> None: ...
    def test(self, cell: Cell) -> bool: ...

class FilterTerm:
    @staticmethod
    def left_of() -> FilterTerm: ...
    @staticmethod
    def right_of() -> FilterTerm: ...
    @staticmethod
    def above() -> FilterTerm: ...
    @staticmethod
    def below() -> FilterTerm: ...
    @staticmethod
    def same_subrow() -> FilterTerm: ...
    @staticmethod
    def same_subcol() -> FilterTerm: ...
    @staticmethod
    def same_subtable() -> FilterTerm: ...
    @staticmethod
    def same_row() -> FilterTerm: ...
    @staticmethod
    def same_col() -> FilterTerm: ...
    @staticmethod
    def not_same_cell() -> FilterTerm: ...
    @staticmethod
    def same_cell() -> FilterTerm: ...
    @staticmethod
    def col_exact(n: int) -> FilterTerm: ...
    @staticmethod
    def col_offset(delta: int) -> FilterTerm: ...
    @staticmethod
    def col_range(from_: int, to: Optional[int] = None) -> FilterTerm: ...
    @staticmethod
    def col_absolute_range(lo: int, hi: Optional[int] = None) -> FilterTerm: ...
    @staticmethod
    def row_exact(n: int) -> FilterTerm: ...
    @staticmethod
    def row_offset(delta: int) -> FilterTerm: ...
    @staticmethod
    def row_absolute_range(lo: int, hi: Optional[int] = None) -> FilterTerm: ...
    @staticmethod
    def pos_exact(n: int) -> FilterTerm: ...
    @staticmethod
    def pos_offset(delta: int) -> FilterTerm: ...
    @staticmethod
    def pos_range(lo: int, hi: Optional[int] = None) -> FilterTerm: ...
    @staticmethod
    def regex_matched(pattern: str) -> FilterTerm: ...
    @staticmethod
    def not_regex_matched(pattern: str) -> FilterTerm: ...
    @staticmethod
    def contains(substring: str) -> FilterTerm: ...
    @staticmethod
    def not_contains(substring: str) -> FilterTerm: ...
    @staticmethod
    def blank() -> FilterTerm: ...
    @staticmethod
    def not_blank() -> FilterTerm: ...
    @staticmethod
    def tagged(tag: str) -> FilterTerm: ...
    @staticmethod
    def not_tagged(tag: str) -> FilterTerm: ...
    @staticmethod
    def same_str() -> FilterTerm: ...
    @staticmethod
    def external(
        name: str, predicate: Callable[[CellDerivedItem, CellDerivedItem], bool]
    ) -> FilterTerm: ...
    @staticmethod
    def custom(
        description: str,
        predicate: Callable[[CellDerivedItem, CellDerivedItem], bool],
    ) -> FilterTerm: ...
    def to_rtl(self) -> str: ...

class ItemFilterConditionSpec:
    @staticmethod
    def bare(constraint: FilterTerm) -> ItemFilterConditionSpec: ...
    @staticmethod
    def and_(*terms: FilterTerm) -> ItemFilterConditionSpec: ...
    @staticmethod
    def or_(*groups: ItemFilterConditionSpec) -> ItemFilterConditionSpec: ...
    @staticmethod
    def custom(
        description: str,
        predicate: Callable[[CellDerivedItem, CellDerivedItem], bool],
    ) -> ItemFilterConditionSpec: ...
    @staticmethod
    def same_subtable() -> ItemFilterConditionSpec: ...
    @staticmethod
    def same_subrow() -> ItemFilterConditionSpec: ...
    @staticmethod
    def same_subcol() -> ItemFilterConditionSpec: ...
    @staticmethod
    def same_cell() -> ItemFilterConditionSpec: ...
    @staticmethod
    def same_row() -> ItemFilterConditionSpec: ...
    @staticmethod
    def same_col() -> ItemFilterConditionSpec: ...
    @staticmethod
    def below() -> ItemFilterConditionSpec: ...
    @staticmethod
    def above() -> ItemFilterConditionSpec: ...
    @staticmethod
    def right_of() -> ItemFilterConditionSpec: ...
    @staticmethod
    def left_of() -> ItemFilterConditionSpec: ...
    def to_rtl(self) -> str: ...

class StringExtractor:
    @staticmethod
    def verbatim() -> StringExtractor: ...
    @staticmethod
    def replaced(regex: str, replacement: str) -> StringExtractor: ...
    @staticmethod
    def whitespace_normalized() -> StringExtractor: ...
    @staticmethod
    def trimmed() -> StringExtractor: ...
    @staticmethod
    def substring(begin: int, end: int) -> StringExtractor: ...
    @staticmethod
    def upper_case() -> StringExtractor: ...
    @staticmethod
    def lower_case() -> StringExtractor: ...
    @staticmethod
    def chain(*steps: StringExtractor) -> StringExtractor: ...
    @staticmethod
    def custom(description: str, fn_: Callable[[str], str]) -> StringExtractor: ...
    def apply(self, input: str) -> str: ...
    def to_rtl(self) -> str: ...

class ProviderSpec:
    UNBOUNDED: int
    cardinality: int
    traversal_order: TraversalOrder
    @staticmethod
    def any(
        condition: ItemFilterConditionSpec,
        cardinality: int = 1,
        traversal_order: Optional[TraversalOrder] = None,
    ) -> ProviderSpec: ...
    @staticmethod
    def val(
        condition: ItemFilterConditionSpec,
        cardinality: int = 1,
        traversal_order: Optional[TraversalOrder] = None,
    ) -> ProviderSpec: ...
    @staticmethod
    def attr(
        condition: ItemFilterConditionSpec,
        traversal_order: Optional[TraversalOrder] = None,
    ) -> ProviderSpec: ...
    @staticmethod
    def aux(
        condition: ItemFilterConditionSpec,
        cardinality: int = 1,
        traversal_order: Optional[TraversalOrder] = None,
    ) -> ProviderSpec: ...
    @staticmethod
    def ctx(text: str, ty: ItemType) -> ProviderSpec: ...
    @staticmethod
    def ctx_attr(text: str) -> ProviderSpec: ...
    @staticmethod
    def ctx_val(text: str) -> ProviderSpec: ...
    @staticmethod
    def ctx_aux(text: str) -> ProviderSpec: ...
    @staticmethod
    def ctx_avp(attr_name: str, value: str) -> ProviderSpec: ...
    def is_context_literal(self) -> bool: ...

class ActionSpec:
    operation_type: OperationType
    inherited: bool
    def __init__(
        self,
        operation_type: OperationType,
        delimiter: Optional[str] = None,
        providers: Sequence[ProviderSpec] = (),
        anchor_pos: Optional[int] = None,
        split_delimiter: Optional[str] = None,
        key_positions: Optional[set[int]] = None,
        inherited: bool = False,
    ) -> None: ...
    @staticmethod
    def rec(
        *providers: Union[ProviderSpec, ItemFilterConditionSpec],
        anchor_pos: Optional[int] = None,
        split_delimiter: Optional[str] = None,
        cardinality: int = 1,
    ) -> ActionSpec: ...
    @staticmethod
    def avp(
        provider: Union[ProviderSpec, ItemFilterConditionSpec, str]
    ) -> ActionSpec: ...
    @staticmethod
    def join(
        *providers: Union[ProviderSpec, ItemFilterConditionSpec],
        key_positions: Union[int, Iterable[int], None] = None,
        cardinality: int = 1,
    ) -> ActionSpec: ...
    @staticmethod
    def fill(
        delimiter: str,
        *providers: Union[ProviderSpec, ItemFilterConditionSpec],
        cardinality: int = 1,
    ) -> ActionSpec: ...
    @staticmethod
    def prefix(
        delimiter: str,
        *providers: Union[ProviderSpec, ItemFilterConditionSpec],
        cardinality: int = 1,
    ) -> ActionSpec: ...
    @staticmethod
    def suffix(
        delimiter: str,
        *providers: Union[ProviderSpec, ItemFilterConditionSpec],
        cardinality: int = 1,
    ) -> ActionSpec: ...
    def as_inherited(self) -> ActionSpec: ...

ContentSpec = Union[
    "AtomicContentSpec",
    "DelimitedContentSpec",
    "CompoundContentSpec",
    "ConditionalContentSpec",
]

class AtomicContentSpec:
    idd: ItemDerivationDirective
    tags: list[str]
    def __init__(
        self,
        idd: ItemDerivationDirective,
        extractor: Optional[StringExtractor] = None,
        tags: Sequence[str] = (),
        actions: Sequence[ActionSpec] = (),
    ) -> None: ...
    @staticmethod
    def val(
        *actions: ActionSpec, extractor: Optional[StringExtractor] = None
    ) -> AtomicContentSpec: ...
    @staticmethod
    def attr(
        *actions: ActionSpec, extractor: Optional[StringExtractor] = None
    ) -> AtomicContentSpec: ...
    @staticmethod
    def aux(
        *actions: ActionSpec, extractor: Optional[StringExtractor] = None
    ) -> AtomicContentSpec: ...
    @staticmethod
    def skip() -> AtomicContentSpec: ...
    @staticmethod
    def val_tagged(
        tag: Union[str, Sequence[str]], *actions: ActionSpec
    ) -> AtomicContentSpec: ...
    def tagged(self, *new_tags: str) -> AtomicContentSpec: ...
    def extract(self, extractor: StringExtractor) -> AtomicContentSpec: ...
    def split_by(self, delimiter: str) -> DelimitedContentSpec: ...
    def then(self, delimiter: str, next: ContentSpec) -> CompoundContentSpec: ...

class DelimitedContentSpec:
    delimiter: str
    atomic_spec: AtomicContentSpec
    def __init__(self, delimiter: str, atomic_spec: AtomicContentSpec) -> None: ...
    def then(self, delimiter: str, next: ContentSpec) -> CompoundContentSpec: ...

class CompoundContentSpec:
    trailing_delimiter: str
    def __init__(
        self,
        segments: Sequence[tuple[str, ContentSpec]],
        trailing_delimiter: str = "",
    ) -> None: ...
    @staticmethod
    def of(
        first: ContentSpec, *rest: tuple[str, ContentSpec]
    ) -> CompoundContentSpec: ...
    def then(self, delimiter: str, next: ContentSpec) -> CompoundContentSpec: ...

class ConditionalContentSpec:
    def __init__(
        self,
        condition: Union[CellMatchCondition, CellPredicate],
        positive: ContentSpec,
        negative: ContentSpec,
    ) -> None: ...

class CellPattern:
    quantifier: Quantifier
    content_spec: Optional[ContentSpec]
    def __init__(
        self,
        condition: Union[CellMatchCondition, CellPredicate, None] = None,
        quantifier: Optional[Quantifier] = None,
        content_spec: Optional[ContentSpec] = None,
    ) -> None: ...
    @staticmethod
    def of(*args: Any) -> CellPattern: ...
    @staticmethod
    def skip(quantifier: Optional[Quantifier] = None) -> CellPattern: ...
    def one_or_more(self) -> CellPattern: ...
    def zero_or_more(self) -> CellPattern: ...
    def zero_or_one(self) -> CellPattern: ...
    def exactly(self, n: int) -> CellPattern: ...

class SubrowPattern:
    quantifier: Quantifier
    def __init__(
        self,
        condition: Union[CellMatchCondition, CellPredicate, None] = None,
        quantifier: Optional[Quantifier] = None,
        cell_patterns: Sequence[CellPattern] = (),
    ) -> None: ...
    @staticmethod
    def of(*args: Any) -> SubrowPattern: ...
    def one_or_more(self) -> SubrowPattern: ...
    def zero_or_more(self) -> SubrowPattern: ...
    def zero_or_one(self) -> SubrowPattern: ...
    def exactly(self, n: int) -> SubrowPattern: ...

class RowPattern:
    quantifier: Quantifier
    def __init__(
        self,
        condition: Union[CellMatchCondition, CellPredicate, None] = None,
        quantifier: Optional[Quantifier] = None,
        subrow_patterns: Sequence[SubrowPattern] = (),
    ) -> None: ...
    @staticmethod
    def of(*args: Any) -> RowPattern: ...
    def one_or_more(self) -> RowPattern: ...
    def zero_or_more(self) -> RowPattern: ...
    def zero_or_one(self) -> RowPattern: ...
    def exactly(self, n: int) -> RowPattern: ...

class SubtablePattern:
    quantifier: Quantifier
    def __init__(
        self,
        condition: Union[CellMatchCondition, CellPredicate, None] = None,
        quantifier: Optional[Quantifier] = None,
        row_patterns: Sequence[RowPattern] = (),
    ) -> None: ...
    @staticmethod
    def of(*args: Any) -> SubtablePattern: ...
    def one_or_more(self) -> SubtablePattern: ...
    def zero_or_more(self) -> SubtablePattern: ...
    def zero_or_one(self) -> SubtablePattern: ...
    def exactly(self, n: int) -> SubtablePattern: ...

RecordsetTransformation = Union[
    "WhitespaceNormalization",
    "AnchorAttributeAtPosition",
    "DelimitedFieldSplit",
    "FieldSplitting",
    "SchemaReordering",
]

class TablePattern:
    def __init__(
        self,
        condition: Union[CellMatchCondition, CellPredicate, None] = None,
        subtable_patterns: Sequence[SubtablePattern] = (),
        transformations: Sequence[RecordsetTransformation] = (),
    ) -> None: ...
    @staticmethod
    def of(*subtables: SubtablePattern) -> TablePattern: ...
    def with_transformations(
        self, *transforms: RecordsetTransformation
    ) -> TablePattern: ...
    def transform(self, rs: Recordset) -> Recordset: ...

# ---------------------------------------------------------------- transformations

class WhitespaceNormalization:
    def __init__(self) -> None: ...
    def apply(self, rs: Recordset) -> Recordset: ...

class AnchorAttributeAtPosition:
    def __init__(self, position: int) -> None: ...
    def apply(self, rs: Recordset) -> Recordset: ...

class DelimitedFieldSplit:
    def __init__(
        self,
        delimiter: str,
        only_attributes: Optional[set[str]] = None,
        anonymous_attribute_template: str = "$a_%i",
    ) -> None: ...
    def apply(self, rs: Recordset) -> Recordset: ...

class FieldSplitting:
    def __init__(
        self,
        attribute: str,
        delimiter: str,
        part_attribute_names: Sequence[str] = (),
    ) -> None: ...
    def apply(self, rs: Recordset) -> Recordset: ...

class SchemaReordering:
    def __init__(self, order: Sequence[str]) -> None: ...
    def apply(self, rs: Recordset) -> Recordset: ...

# ---------------------------------------------------------------- match / interpret

class AtpMatcher:
    @staticmethod
    def match(
        atp: TablePattern,
        syntax: TableSyntax,
        context_items: Optional[Sequence[ContextDerivedItem]] = None,
    ) -> Optional[InterpretableTable]: ...

class TableInterpreter:
    def __init__(self) -> None: ...
    def with_strategy(self, strategy: SchemaConstructionStrategy) -> TableInterpreter: ...
    def with_action_application_strategy(
        self, strategy: ActionApplicationStrategy
    ) -> TableInterpreter: ...
    def with_missing_value_handler(
        self, handler: Callable[[str], Optional[str]]
    ) -> TableInterpreter: ...
    def with_transformations(
        self, transformations: Sequence[RecordsetTransformation]
    ) -> TableInterpreter: ...
    def with_anonymous_attribute_template(self, template: str) -> TableInterpreter: ...
    def interpret(self, table: InterpretableTable) -> Recordset: ...

# ---------------------------------------------------------------- rtl

class Bindings:
    @staticmethod
    def of() -> Bindings: ...
    def cell(self, name: str, predicate: Callable[[Cell], bool]) -> Bindings: ...
    def filter(
        self, name: str, predicate: Callable[[CellDerivedItem, CellDerivedItem], bool]
    ) -> Bindings: ...

class RtlCompiler:
    @staticmethod
    def compile(rtl: str, bindings: Optional[Bindings] = None) -> TablePattern: ...

class AtpToRtlSerializer:
    @staticmethod
    def serialize(pattern: TablePattern) -> str: ...

class RtlCompileError(Exception): ...

def compile(rtl: str, bindings: Optional[Bindings] = None) -> TablePattern: ...
